import { BibleReferenceBook } from '~src/__generated__/graphql';

export const FCBH_API_BASE = 'https://4.dbt.io/api';

export const FCBH_VERSIONS = [
	{
		id: 'ENGKJV2',
		internalId: 6, // AV DB id
		title: 'King James Version (Dramatized)',
	},
];

type BibleBookMeta = {
	fcbhId: string;
	shortName: string;
	fullName: string;
	testament: 'OT' | 'NT';
	bibleReferenceBook: BibleReferenceBook;
};

export const BIBLE_BOOK_METAS: BibleBookMeta[] = [
	{
		fcbhId: 'GEN',
		shortName: 'Gen',
		fullName: 'Genesis',
		testament: 'OT',
		bibleReferenceBook: BibleReferenceBook.Genesis,
	},
	{
		fcbhId: 'EXO',
		shortName: 'Exod',
		fullName: 'Exodus',
		testament: 'OT',
		bibleReferenceBook: BibleReferenceBook.Exodus,
	},
	{
		fcbhId: 'LEV',
		shortName: 'Lev',
		fullName: 'Leviticus',
		testament: 'OT',
		bibleReferenceBook: BibleReferenceBook.Leviticus,
	},
	{
		fcbhId: 'NUM',
		shortName: 'Num',
		fullName: 'Numbers',
		testament: 'OT',
		bibleReferenceBook: BibleReferenceBook.Numbers,
	},
	{
		fcbhId: 'DEU',
		shortName: 'Deut',
		fullName: 'Deuteronomy',
		testament: 'OT',
		bibleReferenceBook: BibleReferenceBook.Deuteronomy,
	},
	{
		fcbhId: 'JOS',
		shortName: 'Josh',
		fullName: 'Joshua',
		testament: 'OT',
		bibleReferenceBook: BibleReferenceBook.Joshua,
	},
	{
		fcbhId: 'JDG',
		shortName: 'Judg',
		fullName: 'Judges',
		testament: 'OT',
		bibleReferenceBook: BibleReferenceBook.Judges,
	},
	{
		fcbhId: 'RUT',
		shortName: 'Ruth',
		fullName: 'Ruth',
		testament: 'OT',
		bibleReferenceBook: BibleReferenceBook.Ruth,
	},
	{
		fcbhId: '1SA',
		shortName: '1Sam',
		fullName: '1 Samuel',
		testament: 'OT',
		bibleReferenceBook: BibleReferenceBook.FirstSamuel,
	},
	{
		fcbhId: '2SA',
		shortName: '2Sam',
		fullName: '2 Samuel',
		testament: 'OT',
		bibleReferenceBook: BibleReferenceBook.SecondSamuel,
	},
	{
		fcbhId: '1KI',
		shortName: '1Kgs',
		fullName: '1 Kings',
		testament: 'OT',
		bibleReferenceBook: BibleReferenceBook.FirstKings,
	},
	{
		fcbhId: '2KI',
		shortName: '2Kgs',
		fullName: '2 Kings',
		testament: 'OT',
		bibleReferenceBook: BibleReferenceBook.SecondKings,
	},
	{
		fcbhId: '1CH',
		shortName: '1Chr',
		fullName: '1 Chronicles',
		testament: 'OT',
		bibleReferenceBook: BibleReferenceBook.FirstChronicles,
	},
	{
		fcbhId: '2CH',
		shortName: '2Chr',
		fullName: '2 Chronicles',
		testament: 'OT',
		bibleReferenceBook: BibleReferenceBook.SecondChronicles,
	},
	{
		fcbhId: 'EZR',
		shortName: 'Ezra',
		fullName: 'Ezra',
		testament: 'OT',
		bibleReferenceBook: BibleReferenceBook.Ezra,
	},
	{
		fcbhId: 'NEH',
		shortName: 'Neh',
		fullName: 'Nehemiah',
		testament: 'OT',
		bibleReferenceBook: BibleReferenceBook.Nehemiah,
	},
	{
		fcbhId: 'EST',
		shortName: 'Esth',
		fullName: 'Esther',
		testament: 'OT',
		bibleReferenceBook: BibleReferenceBook.Esther,
	},
	{
		fcbhId: 'JOB',
		shortName: 'Job',
		fullName: 'Job',
		testament: 'OT',
		bibleReferenceBook: BibleReferenceBook.Job,
	},
	{
		fcbhId: 'PSA',
		shortName: 'Ps',
		fullName: 'Psalms',
		testament: 'OT',
		bibleReferenceBook: BibleReferenceBook.Psalms,
	},
	{
		fcbhId: 'PRO',
		shortName: 'Prov',
		fullName: 'Proverbs',
		testament: 'OT',
		bibleReferenceBook: BibleReferenceBook.Proverbs,
	},
	{
		fcbhId: 'ECC',
		shortName: 'Eccl',
		fullName: 'Ecclesiastes',
		testament: 'OT',
		bibleReferenceBook: BibleReferenceBook.Ecclesiastes,
	},
	{
		fcbhId: 'SNG',
		shortName: 'Song',
		fullName: 'Song of Solomon',
		testament: 'OT',
		bibleReferenceBook: BibleReferenceBook.SongOfSolomon,
	},
	{
		fcbhId: 'ISA',
		shortName: 'Isa',
		fullName: 'Isaiah',
		testament: 'OT',
		bibleReferenceBook: BibleReferenceBook.Isaiah,
	},
	{
		fcbhId: 'JER',
		shortName: 'Jer',
		fullName: 'Jeremiah',
		testament: 'OT',
		bibleReferenceBook: BibleReferenceBook.Jeremiah,
	},
	{
		fcbhId: 'LAM',
		shortName: 'Lam',
		fullName: 'Lamentations',
		testament: 'OT',
		bibleReferenceBook: BibleReferenceBook.Lamentations,
	},
	{
		fcbhId: 'EZK',
		shortName: 'Ezek',
		fullName: 'Ezekiel',
		testament: 'OT',
		bibleReferenceBook: BibleReferenceBook.Ezekiel,
	},
	{
		fcbhId: 'DAN',
		shortName: 'Dan',
		fullName: 'Daniel',
		testament: 'OT',
		bibleReferenceBook: BibleReferenceBook.Daniel,
	},
	{
		fcbhId: 'HOS',
		shortName: 'Hos',
		fullName: 'Hosea',
		testament: 'OT',
		bibleReferenceBook: BibleReferenceBook.Hosea,
	},
	{
		fcbhId: 'JOL',
		shortName: 'Joel',
		fullName: 'Joel',
		testament: 'OT',
		bibleReferenceBook: BibleReferenceBook.Joel,
	},
	{
		fcbhId: 'AMO',
		shortName: 'Amos',
		fullName: 'Amos',
		testament: 'OT',
		bibleReferenceBook: BibleReferenceBook.Amos,
	},
	{
		fcbhId: 'OBA',
		shortName: 'Obad',
		fullName: 'Obadiah',
		testament: 'OT',
		bibleReferenceBook: BibleReferenceBook.Obadiah,
	},
	{
		fcbhId: 'JON',
		shortName: 'Jonah',
		fullName: 'Jonah',
		testament: 'OT',
		bibleReferenceBook: BibleReferenceBook.Jonah,
	},
	{
		fcbhId: 'MIC',
		shortName: 'Mic',
		fullName: 'Micah',
		testament: 'OT',
		bibleReferenceBook: BibleReferenceBook.Micah,
	},
	{
		fcbhId: 'NAM',
		shortName: 'Nah',
		fullName: 'Nahum',
		testament: 'OT',
		bibleReferenceBook: BibleReferenceBook.Nahum,
	},
	{
		fcbhId: 'HAB',
		shortName: 'Hab',
		fullName: 'Habakkuk',
		testament: 'OT',
		bibleReferenceBook: BibleReferenceBook.Habakkuk,
	},
	{
		fcbhId: 'ZEP',
		shortName: 'Zeph',
		fullName: 'Zephaniah',
		testament: 'OT',
		bibleReferenceBook: BibleReferenceBook.Zephaniah,
	},
	{
		fcbhId: 'HAG',
		shortName: 'Hag',
		fullName: 'Haggai',
		testament: 'OT',
		bibleReferenceBook: BibleReferenceBook.Haggai,
	},
	{
		fcbhId: 'ZEC',
		shortName: 'Zech',
		fullName: 'Zechariah',
		testament: 'OT',
		bibleReferenceBook: BibleReferenceBook.Zechariah,
	},
	{
		fcbhId: 'MAL',
		shortName: 'Mal',
		fullName: 'Malachi',
		testament: 'OT',
		bibleReferenceBook: BibleReferenceBook.Malachi,
	},
	{
		fcbhId: 'MAT',
		shortName: 'Matt',
		fullName: 'Matthew',
		testament: 'NT',
		bibleReferenceBook: BibleReferenceBook.Matthew,
	},
	{
		fcbhId: 'MRK',
		shortName: 'Mark',
		fullName: 'Mark',
		testament: 'NT',
		bibleReferenceBook: BibleReferenceBook.Mark,
	},
	{
		fcbhId: 'LUK',
		shortName: 'Luke',
		fullName: 'Luke',
		testament: 'NT',
		bibleReferenceBook: BibleReferenceBook.Luke,
	},
	{
		fcbhId: 'JHN',
		shortName: 'John',
		fullName: 'John',
		testament: 'NT',
		bibleReferenceBook: BibleReferenceBook.John,
	},
	{
		fcbhId: 'ACT',
		shortName: 'Acts',
		fullName: 'Acts',
		testament: 'NT',
		bibleReferenceBook: BibleReferenceBook.Acts,
	},
	{
		fcbhId: 'ROM',
		shortName: 'Rom',
		fullName: 'Romans',
		testament: 'NT',
		bibleReferenceBook: BibleReferenceBook.Romans,
	},
	{
		fcbhId: '1CO',
		shortName: '1Cor',
		fullName: '1 Corinthians',
		testament: 'NT',
		bibleReferenceBook: BibleReferenceBook.FirstCorinthians,
	},
	{
		fcbhId: '2CO',
		shortName: '2Cor',
		fullName: '2 Corinthians',
		testament: 'NT',
		bibleReferenceBook: BibleReferenceBook.SecondCorinthians,
	},
	{
		fcbhId: 'GAL',
		shortName: 'Gal',
		fullName: 'Galatians',
		testament: 'NT',
		bibleReferenceBook: BibleReferenceBook.Galatians,
	},
	{
		fcbhId: 'EPH',
		shortName: 'Eph',
		fullName: 'Ephesians',
		testament: 'NT',
		bibleReferenceBook: BibleReferenceBook.Ephesians,
	},
	{
		fcbhId: 'PHP',
		shortName: 'Phil',
		fullName: 'Philippians',
		testament: 'NT',
		bibleReferenceBook: BibleReferenceBook.Philippians,
	},
	{
		fcbhId: 'COL',
		shortName: 'Col',
		fullName: 'Colossians',
		testament: 'NT',
		bibleReferenceBook: BibleReferenceBook.Colossians,
	},
	{
		fcbhId: '1TH',
		shortName: '1Thess',
		fullName: '1 Thessalonians',
		testament: 'NT',
		bibleReferenceBook: BibleReferenceBook.FirstThessalonians,
	},
	{
		fcbhId: '2TH',
		shortName: '2Thess',
		fullName: '2 Thessalonians',
		testament: 'NT',
		bibleReferenceBook: BibleReferenceBook.SecondThessalonians,
	},
	{
		fcbhId: '1TI',
		shortName: '1Tim',
		fullName: '1 Timothy',
		testament: 'NT',
		bibleReferenceBook: BibleReferenceBook.FirstTimothy,
	},
	{
		fcbhId: '2TI',
		shortName: '2Tim',
		fullName: '2 Timothy',
		testament: 'NT',
		bibleReferenceBook: BibleReferenceBook.SecondTimothy,
	},
	{
		fcbhId: 'TIT',
		shortName: 'Titus',
		fullName: 'Titus',
		testament: 'NT',
		bibleReferenceBook: BibleReferenceBook.Titus,
	},
	{
		fcbhId: 'PHM',
		shortName: 'Phlm',
		fullName: 'Philemon',
		testament: 'NT',
		bibleReferenceBook: BibleReferenceBook.Philemon,
	},
	{
		fcbhId: 'HEB',
		shortName: 'Heb',
		fullName: 'Hebrews',
		testament: 'NT',
		bibleReferenceBook: BibleReferenceBook.Hebrews,
	},
	{
		fcbhId: 'JAS',
		shortName: 'Jas',
		fullName: 'James',
		testament: 'NT',
		bibleReferenceBook: BibleReferenceBook.James,
	},
	{
		fcbhId: '1PE',
		shortName: '1Pet',
		fullName: '1 Peter',
		testament: 'NT',
		bibleReferenceBook: BibleReferenceBook.FirstPeter,
	},
	{
		fcbhId: '2PE',
		shortName: '2Pet',
		fullName: '2 Peter',
		testament: 'NT',
		bibleReferenceBook: BibleReferenceBook.SecondPeter,
	},
	{
		fcbhId: '1JN',
		shortName: '1John',
		fullName: '1 John',
		testament: 'NT',
		bibleReferenceBook: BibleReferenceBook.FirstJohn,
	},
	{
		fcbhId: '2JN',
		shortName: '2John',
		fullName: '2 John',
		testament: 'NT',
		bibleReferenceBook: BibleReferenceBook.SecondJohn,
	},
	{
		fcbhId: '3JN',
		shortName: '3John',
		fullName: '3 John',
		testament: 'NT',
		bibleReferenceBook: BibleReferenceBook.ThirdJohn,
	},
	{
		fcbhId: 'JUD',
		shortName: 'Jude',
		fullName: 'Jude',
		testament: 'NT',
		bibleReferenceBook: BibleReferenceBook.Jude,
	},
	{
		fcbhId: 'REV',
		shortName: 'Rev',
		fullName: 'Revelation',
		testament: 'NT',
		bibleReferenceBook: BibleReferenceBook.Revelation,
	},
];
