ci:
  collect:
  # collect options here
    startServerCommand: npm run start
    url:
      - http://localhost:3000
      - http://localhost:3000/en/sermons/all/page/1

  assert:
  # assert options here

  upload:
  # upload options here

  server:
  # server options here

  wizard:
  # wizard options here
